### PR TITLE
Add Gradle CI

### PR DESCRIPTION
**Pull request by itsnebulalol**
Checks for errors in code, and checks if PR's are okay to merge.

### CODE REVIEW

**Comment by MatthewTGM** [comment]
Kind of good, kind of bad


I'd say this is a chaotic neutral feature.
This can be easily abused.

**Comment by itsnebulalol** [comment]
It can, but probably still needed.

**Comment by Ic0vid** [comment]
i would rather check prs.

**Comment by itsnebulalol** [comment]
You can make it so it doesn't automatically accept, this is just useful for the people that break things on PR's. An open source project should probably have this.

**Pull request closed without merging**
