### PR TITLE
Fix a couple things MatthewTGM did on his PR

### PR DESCRIPTION
**Pull request by itsnebulalol**
MatthewTGM changed a couple of package names and stuff, so I just reverted it back to apollo/io.apollo

### CODE REVIEW

**Comment by NDSDNS** [comment]
Change to be net.apolloclient because we actually own that domain?

**Comment by itsnebulalol** [comment]
Should I? Before some of the classes were in package ga.matthewtgm

**Comment by NDSDNS** [comment]
I'd change all of the package names to net.apolloclient

**Comment by itsnebulalol** [comment]
Okay, I'll try to do a refractor.

**Comment by Ic0vid** [comment]
yes please change all to net.apollo

**Comment by NDSDNS** [comment]
net.apolloclient*

**Pull request merged**
